name: flutter_news
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_svg: ^2.0.4
  dio: ^5.0.2
  shared_preferences: ^2.0.18
  flutter_localizations:
    sdk: flutter
  intl: any
#  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.1
  sqflite: ^2.2.6
  flutter_arch:
    path: ../flutter_arch
  app_data:
    path: package/app_data
  app_widget:
    path: package/app_widget
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.13
  flutter_font_icons: ^2.2.5
  get_storage: ^2.1.1
  floor: ^1.4.1
  flutter_easyloading: ^3.0.5
  # 屏幕适配
  flutter_screenutil: ^5.7.0
  uni_links: ^0.5.1
  mobile_scanner: ^3.2.0
  cookie_jar: ^3.0.0
  dio_cookie_manager: ^2.1.3
  json_annotation: ^4.8.0
  wrapper: ^1.0.2
  flutter_html: ^3.0.0-alpha.6
  html_unescape: ^2.0.0
  card_swiper: ^2.0.4
  webview_flutter: ^4.0.7
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+3
  # 加密安全 SHA
  crypto: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.1
  build_runner: ^2.1.2
  #flutter pub run build_runner build
  #1、flutter packages pub run build_runner clean
  #2、flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  analyzer: any
  dart_code_metrics: any
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0



flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/flutter-logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

flutter_intl:
  enabled: false
